# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-mobile
  pod 'Moya', '~> 8.0'
  pod 'Moya-ModelMapper', '~> 4.1'
  pod 'PKHUD', '~> 4.2'
  
end
